
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* Feature test macros. Flex uses functions that require a minimum set of
 * macros defined. As defining some macros may hide function declarations that
 * user code might use, be conservative and respect user's definitions as much
 * as possible. In glibc, feature test macros may not be all set up until one
 * of the libc header (that includes <features.h>) is included. This creates
 * a circular dependency when we check the macros. <assert.h> is the safest
 * header we can include and does not declare too many functions we don't need.
 */
#if !defined(__GNU_LIBRARY__) && defined(__STDC__)
#include <assert.h>
#endif
#if !(defined(_POSIX_C_SOURCE) || defined(_XOPEN_SOURCE) || \
    defined(_POSIX_SOURCE))
# define _POSIX_C_SOURCE 1 /* Required for fileno() */
# define _POSIX_SOURCE 1
#endif
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C++ systems might need __STDC_LIMIT_MACROS defined before including
 * <stdint.h>, if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[305] =
    {   0,
        0,    0,    0,    0,    0,    0,   80,   78,   75,   76,
        2,   76,   76,   76,    3,   76,   76,   76,   76,   76,
       17,   16,   76,   78,   76,   77,   77,   76,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   76,    8,   79,   11,   79,    9,
       10,   24,   30,   25,   36,   28,   19,   31,   20,   32,
       12,    0,   29,   18,   17,    0,   17,   17,   17,    0,
        0,    0,   17,   16,   16,   16,   16,    0,    0,   16,
       13,   21,   23,   22,   14,    0,   77,   77,    2,    3,
       37,   77,   77,   77,   77,   77,   77,   77,   77,   77,

       45,   77,   77,   77,   77,   77,   77,   53,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   35,
       26,    8,    4,    5,    6,    5,    0,    4,    9,   27,
       18,   18,    0,   17,   15,    0,   17,    0,   17,   17,
       16,    0,   16,    0,   16,   16,   33,   34,    1,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   51,   77,   77,   55,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,    6,    7,    0,   18,   15,   15,    0,
       15,   17,   17,   17,   17,   16,   16,   16,   16,   77,

       77,   77,   38,   77,   40,   41,   77,   77,   77,   77,
       47,   48,   77,   77,   52,   77,   56,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   69,
       77,   77,    6,   18,   18,   15,   15,    0,   15,   15,
       72,   77,   77,   39,   42,   77,   77,   77,   77,   50,
       77,   77,   77,   77,   60,   77,   77,   77,   77,   77,
       77,   67,   77,   77,   71,   15,   15,   77,   77,   77,
       77,   46,   49,   54,   77,   77,   59,   61,   62,   63,
       64,   65,   77,   77,   77,   77,   77,   77,   44,   77,
       77,   66,   77,   77,   73,   77,   43,   57,   58,   68,

       70,   77,   74,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    5,    6,    6,    7,    8,    9,    6,
        6,   10,   11,    6,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   17,   17,    6,    6,   18,
       19,   20,   21,    6,   22,   23,   24,   22,   22,   25,
       26,   26,   27,   26,   26,   28,   26,   26,   26,   26,
       26,   26,   26,   26,   29,   26,   26,   30,   26,   26,
        6,   31,    6,   32,   33,    6,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   26,   43,   44,   45,   46,
       47,   48,   26,   49,   50,   51,   52,   53,   54,   55,
       56,   57,    6,   58,    6,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    2,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    4,    1,    5,    5,    5,    1,    1,    1,
        1,    5,    5,    5,    5,    6,    6,    6,    6,    6,
        2,    1,    6,    5,    5,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6
    } ;

static const flex_int16_t yy_base[313] =
    {   0,
        0,    0,   57,   61,   65,   70,  308, 1219, 1219,  285,
     1219, 1219,  274,   57, 1219,  269,   50,   65,  273,  263,
       89,  135,   62,  260,   63,   74,  107,  259,   70,  142,
      152,  165,   91,  156,  102,   74,  174,  175,  176,  184,
      193,  195,  196,  198,  214,    0, 1219, 1219,  268,    0,
     1219, 1219, 1219, 1219, 1219, 1219, 1219, 1219, 1219, 1219,
     1219,  258, 1219,  236,   48,  241, 1219,  237,  262,    0,
      160,  280,  290,    0, 1219,  297,  305,  335,  345,  339,
      251, 1219, 1219, 1219,  244,  214,    0,  264, 1219, 1219,
     1219,  200,  197,  179,  324,  332,  290,  335,  347,  351,

      355,  365,  367,  369,  370,  384,  387,  388,  396,  398,
      408,  416,  420,  431,  428,  440,  442,  452,  456, 1219,
      432,    0, 1219,   83,   94, 1219,    0, 1219,    0, 1219,
      485,  169,  493,  221,  478,  114,  499,  118,  502,  506,
      388,  137,  531,  145,  536,  530, 1219, 1219, 1219,  157,
      141,  150,  525,  526,  542,  543,  552,  553,  563,  567,
      572,  577,  575,  586,  587,  589,  591,  601,  603,  605,
      606,  620,  625,  636,  634,  639,  648,  656,  659,  667,
      670,  671,  679,  173,    0,  175,  251,  691,  697,  716,
      709,  727,  743,  746,  758,  761,  764,  776,  779,  126,

      118,  116,  764,  765,  773,  775,  776,  787,  785,  797,
      799,  801,  802,  811,  813,  822,  823,  825,  833,  837,
      842,  847,  856,  857,  866,  874,  875,  877,  885,  886,
      894,  896, 1219,  436,  647, 1219,  180,  179,  923,  919,
        0,  101,  100,  895,  912,  923,  927,  938,  941,  939,
      955,  950,  958,  969,  970,  972,  973,  987,  984,  992,
     1002, 1003, 1007, 1004, 1018, 1041, 1045,  101,   80, 1030,
     1034, 1042, 1045, 1053, 1057, 1065, 1056, 1068, 1073, 1076,
     1077, 1085, 1088, 1087, 1096,   58,   77, 1104, 1105, 1107,
     1116, 1119, 1121, 1131,    0,   51, 1130, 1139, 1140, 1141,

     1142,   39,    0, 1219, 1189, 1195, 1198, 1200, 1206, 1212,
       81,   66
    } ;

static const flex_int16_t yy_def[313] =
    {   0,
      304,    1,  305,  305,  306,  306,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  307,  307,  304,  308,  307,
      307,  307,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,  309,  304,  304,  304,  310,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,   21,  304,  304,  304,  304,  311,
      304,  304,  304,   22,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  308,   32,  304,  304,
      304,  308,  308,  308,   32,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,  304,
       32,  309,  304,  304,  304,  304,  312,  304,  310,  304,
      304,  304,  304,  304,  311,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  308,
      308,  308,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,  304,  312,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  308,

      308,  308,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,  304,  304,  304,  304,  304,  304,  304,  304,
      308,  308,  308,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,  304,  304,  308,  308,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,  308,  308,   32,   32,   32,
       32,   32,   32,   32,  308,  308,   32,   32,   32,   32,

       32,  308,  308,    0,  304,  304,  304,  304,  304,  304,
      304,  304
    } ;

static const flex_int16_t yy_nxt[1278] =
    {   0,
        8,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   22,   23,   24,   25,
       12,   26,   26,   26,   26,   26,   26,   27,   26,   26,
       12,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       26,   37,   26,   38,   26,   26,   26,   26,   39,   40,
       41,   42,   43,   44,   26,   26,   26,   45,   47,   47,
       57,   48,   47,   47,   54,   48,   47,   47,   58,   47,
      185,   47,   47,   51,   47,   55,   59,  304,   51,   81,
       82,   84,   85,   60,   61,  135,   86,   49,   87,   87,
       87,   49,   92,   93,  303,   49,   94,  184,  184,  302,

       49,   64,  304,   65,   65,   66,   87,   88,  184,  184,
      296,   89,  295,   67,   88,   90,   68,   69,   70,   86,
      107,   87,   87,   87,   88,  287,   71,   67,  100,  137,
      137,   88,   68,  139,  139,   88,   72,  101,  286,   87,
       69,  269,   88,   70,  268,  105,   73,   64,  106,   74,
       74,   74,  143,  143,   86,  243,   87,   87,   87,   75,
      145,  145,   76,   77,   86,  242,   87,   87,   87,  241,
      136,  136,   78,   75,   87,  137,  137,   86,   76,   87,
       87,   87,   79,  202,   87,  201,   77,  233,  233,   88,
      187,  187,   80,   95,  239,  239,   88,   87,   97,  102,

       96,  103,   88,  200,  236,   98,  133,   88,   88,   88,
      104,   99,  108,  111,   88,   88,   88,   88,  236,  109,
       88,  110,   88,  152,  112,  113,   88,  190,   88,   88,
       88,   88,  120,   88,  114,   88,   88,  115,  119,   88,
      117,   88,  118,  151,   88,   67,  150,   88,  116,  149,
      131,  131,  131,   64,   88,   66,   66,   66,   71,   67,
       88,   67,  148,  132,  134,  234,  235,  235,   72,  147,
      130,  121,  123,  133,   71,   67,  123,   91,   83,  132,
      134,   63,  124,  125,   72,   62,   67,   56,  123,   68,
      138,  138,   53,  132,  134,  139,  139,   88,  123,   71,

       67,  126,  126,   52,   88,   68,  126,  304,  304,   72,
       88,  304,  304,  126,   67,  304,  126,  140,  126,   68,
      126,   75,  127,   88,  141,  128,  304,   71,   67,   75,
       88,  304,   76,  140,   78,   75,   88,   72,  304,  155,
      141,  304,   78,   75,   79,  142,  142,  140,   76,  304,
      143,  143,   79,  304,  141,  144,  144,   88,  304,  304,
      145,  145,   76,   75,   88,   88,  146,  304,  156,  154,
       88,  304,   88,  304,  153,   88,   78,   75,   88,  304,
       88,   88,  146,  304,   88,  304,   79,   88,   88,  158,
      304,   88,  157,   88,  304,   88,  146,   88,   88,  304,

       88,   88,   88,   88,  304,   88,  159,   88,  304,   88,
       88,   88,   75,   88,  160,   88,  163,   88,  161,  162,
       88,   88,  304,  304,   88,   78,   75,   88,   88,   88,
       88,   88,  164,   88,   88,   79,   88,  165,   88,  166,
      304,   88,   88,  168,   88,  304,  167,  169,   88,   88,
      234,  235,  235,   88,   88,  304,   88,  170,  171,  173,
       88,   88,  172,  304,  175,   88,   88,  304,   88,  177,
      304,   88,   88,   88,   88,   88,  174,   88,   88,  176,
       88,  304,   88,  179,  304,   88,   88,  178,   88,   88,
      304,  180,   88,  181,  304,  182,   88,  183,   88,  131,

      131,  131,   88,  186,  186,  188,  189,  304,  187,  187,
      304,  304,  132,  192,  193,  193,  194,  195,  195,  304,
      304,  188,  133,   67,  304,  190,   67,  304,  132,  189,
       67,  304,  304,  134,  304,  191,  304,   67,  304,  304,
       67,  304,  132,   71,   67,  196,  197,  197,  304,  134,
      198,  199,  199,   72,   75,   75,  304,  141,   88,  204,
       75,  304,  304,  134,  304,   88,   88,   78,   75,   75,
      304,  203,   88,  141,   75,   88,   88,   79,  304,  205,
      304,  304,   88,   88,  304,   88,  209,  141,   88,   88,
      304,  206,   88,   88,  304,  304,   88,  210,   88,   88,

       88,  207,  208,   88,  211,   88,  304,   88,  214,   88,
       88,  304,   88,   88,  213,   88,  212,   88,   88,   88,
       88,   88,   88,   88,   88,  304,   88,   88,  304,   88,
      216,   88,   88,  215,   88,   88,   88,   88,   88,   88,
      217,   88,  304,   88,  218,   88,   88,   88,  304,   88,
      304,   88,   88,   88,  304,  219,  304,  220,   88,  304,
       88,  234,  235,  235,  304,   88,   88,   88,  221,   88,
      222,   88,   88,  223,   88,  304,   88,  304,  304,   88,
       88,   88,   88,  304,  224,   88,  304,  304,   88,   88,
      225,  304,   88,  227,   88,  304,   88,  304,  226,   88,

       88,  304,   88,   88,  231,  228,  230,   88,  229,  304,
       88,   88,   88,   88,  304,  236,   88,   88,  237,   88,
      304,  236,  232,  304,  188,   88,  238,  238,  304,  236,
      304,  239,  239,  236,  237,  236,  240,  304,  190,  304,
      188,  192,  193,  193,  190,  304,  304,  236,  237,  304,
      304,   67,  240,  304,  188,  304,  190,  192,  193,  193,
      194,  195,  195,  304,  304,   67,  240,   67,  304,  304,
       67,  304,  194,  195,  195,  196,  197,  197,  196,  197,
      197,   67,   67,  304,   67,   75,  304,  304,   75,  304,
      198,  199,  199,  198,  199,  199,   67,   88,   88,   75,

       75,  304,   75,   75,   88,   88,   88,  244,   88,   88,
       88,   88,  304,   88,   75,   88,   88,   75,   88,   88,
       88,   88,   88,  304,  304,   88,  245,   88,  246,  304,
       88,   88,   88,   88,   88,   88,  247,   88,  304,   88,
      248,   88,   88,   88,   88,   88,   88,   88,   88,  304,
      249,   88,  304,   88,  304,   88,   88,   88,   88,   88,
      304,  250,   88,   88,  304,   88,   88,  251,   88,   88,
       88,   88,  304,   88,  252,   88,  304,   88,  304,   88,
       88,  253,   88,   88,  256,  254,  304,   88,   88,   88,
       88,  304,  255,   88,  304,  304,   88,   88,  258,   88,

      304,  259,  257,   88,  304,  304,   88,   88,   88,  260,
       88,  261,   88,  304,   88,   88,  304,   88,   88,   88,
       88,   88,  262,   88,  263,   88,   88,   88,   88,   88,
      304,   88,   88,  265,   88,   88,   88,  266,  267,  267,
       88,   88,   88,  236,  264,   88,  237,  236,  304,  304,
      304,  304,   88,  304,  304,  304,   88,  236,   88,  304,
       88,  236,  237,   88,  304,  304,  190,   88,  270,   88,
      271,   88,   88,   88,   88,  272,  237,  304,   88,   88,
      304,   88,  304,   88,   88,   88,  273,   88,   88,  304,
       88,   88,  274,  304,  304,   88,   88,  304,   88,  276,

      275,   88,   88,   88,   88,   88,   88,  304,  278,   88,
       88,  279,   88,   88,  277,   88,   88,   88,   88,   88,
       88,  304,  280,  304,   88,   88,  304,   88,  304,  304,
       88,  304,  282,   88,  281,   88,   88,   88,   88,  283,
       88,  304,   88,   88,   88,  285,  304,   88,   88,   88,
       88,   88,  284,   88,  304,  266,  267,  267,   88,  266,
      267,  267,  304,   88,   88,  236,  304,   88,  304,  236,
       88,  304,  304,  304,   88,   88,   88,  304,   88,  236,
       88,  288,   88,  236,  289,   88,   88,  304,   88,   88,
       88,   88,  304,   88,  290,  304,   88,   88,   88,   88,

      291,   88,   88,   88,  304,   88,   88,  304,   88,   88,
       88,   88,  304,   88,   88,  304,   88,   88,   88,   88,
       88,   88,   88,   88,  293,   88,  292,   88,   88,   88,
      304,   88,  304,   88,   88,  304,   88,   88,   88,  294,
       88,  297,   88,  304,   88,   88,  304,   88,  304,   88,
       88,   88,   88,   88,   88,  298,   88,  300,  304,   88,
      304,   88,   88,   88,   88,   88,  299,   88,  301,  304,
       88,   88,   88,   88,   88,   88,   88,   88,  304,   88,
       88,   88,   88,  304,  304,   88,   88,   88,   88,   46,
       46,   46,   46,   46,   46,   50,   50,   50,   50,   50,

       50,   88,   88,   88,   87,   87,  122,  304,  122,  122,
      122,  122,  129,  304,  304,  129,  129,  129,    7,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304
    } ;

static const flex_int16_t yy_chk[1278] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
       17,    3,    4,    4,   14,    4,    5,    5,   17,    5,
      312,    6,    6,    5,    6,   14,   18,   65,    6,   23,
       23,   25,   25,   18,   18,  311,   26,    3,   26,   26,
       26,    4,   29,   29,  302,    5,   29,  124,  124,  296,

        6,   21,   65,   21,   21,   21,   26,   36,  125,  125,
      287,   27,  286,   21,   36,   27,   21,   21,   21,   27,
       36,   27,   27,   27,   33,  269,   21,   21,   33,  136,
      136,   33,   21,  138,  138,   35,   21,   33,  268,   27,
       21,  243,   35,   21,  242,   35,   21,   22,   35,   22,
       22,   22,  142,  142,   30,  202,   30,   30,   30,   22,
      144,  144,   22,   22,   31,  201,   31,   31,   31,  200,
       71,   71,   22,   22,   30,   71,   71,   32,   22,   32,
       32,   32,   22,  152,   31,  151,   22,  184,  184,   34,
      186,  186,   22,   30,  238,  238,   34,   32,   32,   34,

       31,   34,   34,  150,  237,   32,  132,   37,   38,   39,
       34,   32,   37,   39,   37,   38,   39,   40,  237,   37,
       37,   38,   39,   94,   40,   40,   41,  237,   42,   43,
       40,   44,   45,   41,   40,   42,   43,   40,   44,   41,
       42,   42,   43,   93,   44,  134,   92,   45,   41,   86,
       64,   64,   64,   66,   45,   66,   66,   66,  134,  134,
       45,   68,   85,   64,   68,  187,  187,  187,  134,   81,
       62,   45,   49,   64,   68,   68,   49,   28,   24,   64,
       68,   20,   49,   49,   68,   19,   69,   16,   49,   69,
       72,   72,   13,   64,   68,   72,   72,   88,   49,   69,

       69,   49,   49,   10,   88,   69,   49,    7,    0,   69,
       88,    0,    0,   49,   73,    0,   49,   73,   49,   69,
       49,   76,   49,   97,   76,   49,    0,   73,   73,   77,
       97,    0,   77,   73,   76,   76,   97,   73,    0,   97,
       76,    0,   77,   77,   76,   78,   78,   73,   77,    0,
       78,   78,   77,    0,   76,   79,   79,   95,    0,    0,
       79,   79,   77,   80,   95,   96,   80,    0,   98,   96,
       95,    0,   96,    0,   95,   98,   80,   80,   96,    0,
       99,   98,   80,    0,  100,    0,   80,   99,  101,  100,
        0,  100,   99,   99,    0,  101,   80,  100,  102,    0,

      103,  101,  104,  105,    0,  102,  101,  103,    0,  104,
      105,  102,  141,  103,  102,  104,  105,  106,  103,  104,
      107,  108,    0,    0,  106,  141,  141,  107,  108,  109,
      106,  110,  106,  107,  108,  141,  109,  107,  110,  109,
        0,  111,  109,  110,  110,    0,  109,  111,  111,  112,
      234,  234,  234,  113,  111,    0,  112,  111,  111,  113,
      113,  115,  112,    0,  114,  121,  113,    0,  115,  115,
        0,  114,  121,  116,  115,  117,  113,  114,  121,  114,
      116,    0,  117,  117,    0,  118,  116,  116,  117,  119,
        0,  117,  118,  118,    0,  118,  119,  119,  118,  131,

      131,  131,  119,  133,  133,  135,  135,    0,  133,  133,
        0,    0,  131,  137,  137,  137,  139,  139,  139,    0,
        0,  135,  131,  137,    0,  135,  139,    0,  131,  135,
      140,    0,    0,  140,    0,  135,    0,  137,    0,    0,
      139,    0,  131,  140,  140,  143,  143,  143,    0,  140,
      145,  145,  145,  140,  146,  143,    0,  146,  153,  154,
      145,    0,    0,  140,    0,  153,  154,  146,  146,  143,
        0,  153,  154,  146,  145,  155,  156,  146,    0,  155,
        0,    0,  155,  156,    0,  157,  158,  146,  155,  156,
        0,  156,  157,  158,    0,    0,  159,  159,  157,  158,

      160,  157,  157,  159,  160,  161,    0,  160,  163,  159,
      162,    0,  161,  160,  162,  163,  161,  162,  161,  164,
      165,  163,  166,  162,  167,    0,  164,  165,    0,  166,
      166,  167,  164,  165,  168,  166,  169,  167,  170,  171,
      168,  168,    0,  169,  169,  170,  171,  168,    0,  169,
        0,  170,  171,  172,    0,  170,    0,  171,  173,    0,
      172,  235,  235,  235,    0,  173,  172,  175,  172,  174,
      173,  173,  176,  174,  175,    0,  174,    0,    0,  176,
      175,  177,  174,    0,  175,  176,    0,    0,  177,  178,
      176,    0,  179,  178,  177,    0,  178,    0,  177,  179,

      180,    0,  178,  181,  182,  179,  181,  180,  180,    0,
      181,  182,  183,  180,    0,  188,  181,  182,  188,  183,
        0,  189,  183,    0,  189,  183,  190,  190,    0,  188,
        0,  190,  190,  191,  188,  189,  191,    0,  188,    0,
      189,  192,  192,  192,  189,    0,    0,  191,  188,    0,
        0,  192,  191,    0,  189,    0,  191,  193,  193,  193,
      194,  194,  194,    0,    0,  192,  191,  193,    0,    0,
      194,    0,  195,  195,  195,  196,  196,  196,  197,  197,
      197,  193,  195,    0,  194,  196,    0,    0,  197,    0,
      198,  198,  198,  199,  199,  199,  195,  203,  204,  196,

      198,    0,  197,  199,  203,  204,  205,  204,  206,  207,
      203,  204,    0,  205,  198,  206,  207,  199,  209,  205,
      208,  206,  207,    0,    0,  209,  207,  208,  208,    0,
      210,  209,  211,  208,  212,  213,  209,  210,    0,  211,
      210,  212,  213,  210,  214,  211,  215,  212,  213,    0,
      213,  214,    0,  215,    0,  216,  217,  214,  218,  215,
        0,  214,  216,  217,    0,  218,  219,  216,  216,  217,
      220,  218,    0,  219,  218,  221,    0,  220,    0,  219,
      222,  219,  221,  220,  222,  220,    0,  222,  221,  223,
      224,    0,  221,  222,    0,    0,  223,  224,  224,  225,

        0,  225,  223,  224,    0,    0,  225,  226,  227,  226,
      228,  227,  225,    0,  226,  227,    0,  228,  229,  230,
      226,  227,  228,  228,  229,  229,  230,  231,  244,  232,
        0,  229,  230,  232,  231,  244,  232,  239,  239,  239,
      231,  244,  232,  240,  231,  245,  240,  239,    0,    0,
        0,    0,  245,    0,    0,    0,  246,  240,  245,    0,
      247,  239,  240,  246,    0,    0,  240,  247,  246,  246,
      247,  248,  250,  247,  249,  248,  240,    0,  248,  250,
        0,  249,    0,  252,  248,  250,  249,  249,  251,    0,
      252,  253,  251,    0,    0,  251,  252,    0,  253,  253,

      252,  251,  254,  255,  253,  256,  257,    0,  256,  254,
      255,  257,  256,  257,  254,  254,  255,  259,  256,  257,
      258,    0,  258,    0,  259,  260,    0,  258,    0,    0,
      259,    0,  260,  258,  259,  261,  262,  264,  260,  261,
      263,    0,  261,  262,  264,  264,    0,  263,  261,  262,
      264,  265,  263,  263,    0,  266,  266,  266,  265,  267,
      267,  267,    0,  270,  265,  266,    0,  271,    0,  267,
      270,    0,    0,    0,  271,  272,  270,    0,  273,  266,
      271,  270,  272,  267,  271,  273,  274,    0,  272,  277,
      275,  273,    0,  274,  275,    0,  277,  275,  276,  274,

      276,  278,  277,  275,    0,  276,  279,    0,  278,  280,
      281,  276,    0,  279,  278,    0,  280,  281,  282,  279,
      284,  283,  280,  281,  284,  282,  283,  284,  283,  285,
        0,  282,    0,  284,  283,    0,  285,  288,  289,  285,
      290,  288,  285,    0,  288,  289,    0,  290,    0,  291,
      288,  289,  292,  290,  293,  290,  291,  293,    0,  292,
        0,  293,  291,  297,  294,  292,  291,  293,  294,    0,
      297,  294,  298,  299,  300,  301,  297,  294,    0,  298,
      299,  300,  301,    0,    0,  298,  299,  300,  301,  305,
      305,  305,  305,  305,  305,  306,  306,  306,  306,  306,

      306,  307,  307,  307,  308,  308,  309,    0,  309,  309,
      309,  309,  310,    0,    0,  310,  310,  310,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 3 "lexer.l"
#include "tokens-manual.h"
#include <math.h>
#include <ctype.h>
#include <string.h>
#define INTLONG 500
#define LLU 501
#define newline 600
#define PUNCTUATION 601
char* yylval;
char* placeholder;
char* name = "stdin";
int isFloat=0;
int line = 1;
#line 857 "lex.yy.c"

#line 859 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define CHAR 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 28 "lexer.l"


#line 1081 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 305 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1219 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "lexer.l"
{yylval = strdup(yytext); return NAME;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "lexer.l"
{BEGIN(STRING);placeholder= malloc(sizeof(char));sprintf(placeholder,"");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "lexer.l"
{BEGIN(CHAR);placeholder= malloc(sizeof(char));sprintf(placeholder,"");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "lexer.l"
{strcat(placeholder,&yytext[1]);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "lexer.l"
{strcat(placeholder, yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "lexer.l"
{long temp = strtol(yytext+1,NULL,8);char* storage=malloc(sizeof(char));
        if(temp > 255){
                fprintf("%s:%d:Hex escape sequence %s out of range",name,line); 
                temp = 255;
        }
        if(isprint(temp)==0){
                sprintf(storage,"\\%03o",temp);
        }
        else{
                sprintf(storage,"%c",temp);
        }
        strcat(placeholder,storage);free(storage);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "lexer.l"
{long temp = strtol(yytext+2,NULL,16);char* storage=malloc(sizeof(char));
        if(temp > 255){
                fprintf("%s:%d:Hex escape sequence %s out of range",name,line); 
                temp = 255;
        }
        if(isprint(temp)==0){
                sprintf(storage,"\\%03o",temp);
        }
        else{
                sprintf(storage,"%c",temp);
        }
        strcat(placeholder,storage);free(storage);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 61 "lexer.l"
{strcat(placeholder, yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "lexer.l"
{strcat(placeholder, yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "lexer.l"
{BEGIN(INITIAL);
        if(strlen(placeholder) >1){
                fprintf("%s:%d:WARNING:Unsupported multibyte character literal truncated to first byte \n",name,line); 
                placeholder[1] = '\0';
        }
        yylval = strdup(placeholder); free(placeholder);return CHAR;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 "lexer.l"
{BEGIN(INITIAL);yylval = strdup(placeholder); free(placeholder);return STRING;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 "lexer.l"
{return INDSEL;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 72 "lexer.l"
{return SHL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 73 "lexer.l"
{return SHR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 74 "lexer.l"
{char * end;long temp = strtol(yytext+2,&end,16);char* storage= malloc(sizeof(char));sprintf(storage,"%ld",temp);strcat(storage,end);yylval =strdup(storage);free(storage);return NUMBER;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 75 "lexer.l"
{yylval = strdup(yytext);return NUMBER;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 "lexer.l"
{char * end;long temp = strtol(yytext,&end,8);char* storage= malloc(sizeof(char));sprintf(storage,"%ld",temp);strcat(storage,end);yylval =strdup(storage);free(storage);return NUMBER;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 77 "lexer.l"
{yylval = strdup(yytext);isFloat = 1; return NUMBER; }   
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "lexer.l"
{return PLUSPLUS;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 79 "lexer.l"
{return MINUSMINUS;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 80 "lexer.l"
{return LTEQ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 81 "lexer.l"
{return GTEQ;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 82 "lexer.l"
{return EQEQ;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 83 "lexer.l"
{return NOTEQ;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 84 "lexer.l"
{return LOGAND;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 85 "lexer.l"
{return LOGOR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "lexer.l"
{return ELLIPSIS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 "lexer.l"
{return TIMESEQ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 "lexer.l"
{return DIVEQ;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "lexer.l"
{return MODEQ;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "lexer.l"
{return PLUSEQ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "lexer.l"
{return MINUSEQ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "lexer.l"
{return SHLEQ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "lexer.l"
{return SHREQ;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "lexer.l"
{return OREQ;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "lexer.l"
{return ANDEQ;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 96 "lexer.l"
{return XOREQ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 97 "lexer.l"
{return AUTO;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 98 "lexer.l"
{return BREAK;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 99 "lexer.l"
{return CASE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "lexer.l"
{return CHAR;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 101 "lexer.l"
{return CONST;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 102 "lexer.l"
{return CONTINUE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 103 "lexer.l"
{return DEFAULT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 104 "lexer.l"
{return DO;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "lexer.l"
{return DOUBLE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 106 "lexer.l"
{return ELSE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 107 "lexer.l"
{return ENUM;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 108 "lexer.l"
{return EXTERN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 109 "lexer.l"
{return FLOAT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 110 "lexer.l"
{return FOR;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 111 "lexer.l"
{return GOTO;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 112 "lexer.l"
{return IF;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 113 "lexer.l"
{return INLINE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 114 "lexer.l"
{return INT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 115 "lexer.l"
{return LONG;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 116 "lexer.l"
{return REGISTER;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 117 "lexer.l"
{return RESTRICT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 118 "lexer.l"
{return RETURN;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 119 "lexer.l"
{return SHORT;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 120 "lexer.l"
{return SIGNED;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 121 "lexer.l"
{return SIZEOF;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 122 "lexer.l"
{return STATIC;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 123 "lexer.l"
{return STRUCT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 124 "lexer.l"
{return SWITCH;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 125 "lexer.l"
{return TYPEDEF;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 126 "lexer.l"
{return UNION;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 127 "lexer.l"
{return UNSIGNED;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 128 "lexer.l"
{return VOID;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 129 "lexer.l"
{return VOLATILE;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 130 "lexer.l"
{return WHILE;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 131 "lexer.l"
{return _BOOL;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 132 "lexer.l"
{return _COMPLEX;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 133 "lexer.l"
{return _IMAGINARY;}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 134 "lexer.l"
{line = line + 1;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 135 "lexer.l"
{yylval = strdup(yytext);return PUNCTUATION;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 136 "lexer.l"
{yylval = strdup(yytext); return IDENT;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 137 "lexer.l"
{fprintf(stderr, "Error: Unknown token %s\n", yytext);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 139 "lexer.l"
ECHO;
	YY_BREAK
#line 1561 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 305 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 305 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 304);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 139 "lexer.l"

main(){
        int t;
        yylval = malloc(sizeof(float));
        
        char* name = "stdin";
        printf("File name is %s\n", __FILE__);
        while (t = yylex())
        {
                switch(t)
                        {
                                case NAME: printf("Name is %s\n", yylval); name = yylval; break;
                                
                                case INDSEL: printf("%s\t\%d\tINDSEL\n",name,line); break;
                                case IDENT:printf("%s\t%d\tIDENT\t%s\n",name,line,yylval); break;
                                case CHAR:  printf("%s\t%d\tCHARLITERAL\t%s\n",name,line,yylval); break;
                                case STRING: printf("%s\t%d\tSTRING\t%s\n",name,line,yylval); break;
                                case PUNCTUATION: printf("%s\t%d\t%s\n",name,line,yylval); break;
                                case SHL:printf("%s\t%d\tSHL\n", name, line); break;
                                case SHR: printf("%s\t%d\tSHR\n", name, line); break;
                                
                                case PLUSPLUS: printf("%s\t%d\tPLUSPLUS\n", name, line); break;
                                case MINUSMINUS:printf("%s\t%d\tMINUSMINUS\n", name, line); break;
                                case LTEQ: printf("%s\t%d\tLTEQ\n", name, line); break;
                                case GTEQ: printf("%s\t%d\tGTEQ\n", name, line); break;
                                case EQEQ: printf("%s\t%d\tEQEQ\n", name, line); break;
                                case NOTEQ: printf("%s\t%d\tNOTEQ\n", name, line); break;
                                case LOGAND: printf("%s\t%d\tLOGAND\n", name, line); break;
                                case LOGOR: printf("%s\t%d\tLOGOR\n", name, line); break;
                                case ELLIPSIS: printf("%s\t%d\tELLIPSIS\n", name, line); break;
                                case TIMESEQ: printf("%s\t%d\tTIMESEQ\n", name, line); break;
                                case DIVEQ: printf("%s\t%d\tDIVEQ\n", name, line); break;
                                case MODEQ:printf("%s\t%d\tMODEQ\n", name, line); break;
                                case PLUSEQ: printf("%s\t%d\tPLUSEQ\n", name, line); break;
                                case MINUSEQ: printf("%s\t%d\tMINUSEQ\n", name, line); break;
                                case SHLEQ: printf("%s\t%d\tSHLEQ\n", name, line); break;
                                case SHREQ: printf("%s\t%d\tSHREQ\n", name, line); break;
                                case ANDEQ: printf("%s\t%d\tANDEQ\n", name, line); break;
                                case OREQ: printf("%s\t%d\tOREQ\n", name, line); break;
                                case XOREQ: printf("%s\t%d\tXOREQ\n", name, line); break;
                                case NUMBER:;
                                        double floatVal;
                                        char* copyVal;
                                        
                                        int charCount =0;
                                        long eSign = 0;
                                        long eVal = 0;
                                        int pSign =0;
                                        int pVal =0;
                                        char* type = malloc(1024);
                                        char* end;
                                        char* eCheck = strchr(yylval,'e');
                                        char* pCheck = strchr(yylval,'p');
                                        if ( eCheck!= NULL){
                                                isFloat = 1;
                                                charCount+=1;
                                                
                                                if(isdigit(eCheck[1])){
                                                        eSign = 1;
                                                        eVal = strtol(yylval+(int)(eCheck-yylval)+1,NULL,10);
                                                }
                                                else if (yylval[strlen(yylval)-2] == '-'){
                                                        charCount+=1;
                                                        eSign = -1;
                                                        eVal = strtol(yylval+(int)(eCheck-yylval)+2,NULL,10);
                                                }
                                                else{
                                                        charCount+=1;
                                                        eSign = 1;
                                                        eVal = strtol(yylval+(int)(eCheck-yylval)+2,NULL,10);
                                                }
                                                
                                                
                                                
                                        }
                                        
                                        long test = eVal;
                                        while (test>0){
                                                test = test/10;
                                                charCount++;
                                        }
                                        if ( pCheck!= NULL){
                                                isFloat = 1;
                                                charCount+=1;
                                                
                                                if(isdigit(pCheck[1])){
                                                        pSign = 1;
                                                        pVal = strtol(yylval+(int)(pCheck-yylval)+1,NULL,10);
                                                }
                                                else if (yylval[strlen(yylval)-2] == '-'){
                                                        charCount+=1;
                                                        pSign = -1;
                                                        pVal = strtol(yylval+(int)(pCheck-yylval)+2,NULL,10);
                                                }
                                                else{
                                                        charCount+=1;
                                                        pSign = 1;
                                                        pVal = strtol(yylval+(int)(pCheck-yylval)+2,NULL,10);
                                                }
                                                
                                                
                                                
                                        }
                                        
                                        test = pVal;
                                        while (test>0){
                                                test = test/10;
                                                charCount++;
                                        }
                                        if(!isFloat){
                                                
                                                if((strchr(yylval,'U') != NULL) || (strchr(yylval,'u') != NULL))
                                                {
                                                        strcat(type,"UNSIGNED,");
                                                        charCount++;
                                                }
                                                if(strstr(yylval,"LL") != NULL)
                                                {
                                                        strcat(type,"LONGLONG");
                                                        charCount+=2;

                                                }
                                                else if( (strchr(yylval,'L') != NULL) || (strchr(yylval,'l') != NULL))
                                                {
                                                        strcat(type,"LONG");
                                                        charCount++;

                                                }
                                                else {

                                                        strcat(type,"INT");
                                                }

                                                
                                                
                                        }
                                        
                                        
                                        if(isFloat){
                                                
                                                if( (strchr(yylval,'L') != NULL) || (strchr(yylval,'l') != NULL))
                                                {
                                                        strcat(type,"LONGDOUBLE");
                                                        charCount++;

                                                }
                                                else if(strchr(yylval,'f')!= NULL || strchr(yylval,'F')!= NULL  ){
                                                        strcat(type,"Float");
                                                        charCount++;
                                                }
                                                else{
                                                        strcat(type,"DOUBLE");
                                                }
                                                
                                                //memcpy(copyVal,yylval,strlen(yylval)-charCount);
                                               // floatVal = atof(copyVal);
                                                
                                        }
                                        
                                        
                                        if(charCount!=0){yylval[strlen(yylval)-charCount] = '\0';}
                                        floatVal = atof(yylval);
                                        
                                        if(isFloat){
                                                long double temp = floatVal * pow(10,eSign*eVal) * pow(2,pSign*pVal);
                                                sprintf(yylval,"%Lg",temp);
                                                printf("%s\t%d\tNUMBER\tREAL\t%s\t%s\n",name,line, yylval,type);  
                                        }
                                        else{
                                                long int temp = atoi(yylval) * pow(10,eSign*eVal) * pow(2,pSign*pVal);
                                                sprintf(yylval,"%lld",temp);
                                                printf("%s\t%d\tNUMBER\tINTEGER\t%s\t%s\n",name,line, yylval,type);
                                        }
                                        
                                        break;
                                
                                case AUTO: printf("%s\t%d\tAUTO\n", name, line); break;
                                case BREAK: printf("%s\t%d\tBREAK\n", name,line); break;
                                case CASE: printf("%s\t%d\tCASE\n", name, line); break;
                                case CONST: printf("%s\t%d\tCONST\n", name, line); break;
                                case CONTINUE: printf("%s\t%d\tCONTINUE\n", name, line); break;
                                case DEFAULT: printf("%s\t%d\tDEFAULT\n",name, line); break;
                                case DO: printf("%s\t%d\tDO\n", name, line); break;
                                case DOUBLE: printf("%s\t%d\tDOUBLE\n", name, line); break;
                                case ELSE: printf("%s\t%d\tELSE\n",name, line); break;
                                case ENUM: printf("%s\t%d\tENUM\n", name, line); break;
                                case EXTERN: printf("%s\t%d\tEXTERN\n", name, line); break;
                                case FLOAT: printf("%s\t%d\tFLOAT\n", name, line); break;
                                case FOR: printf("%s\t%d\tFOR\n", name, line); break;
                                case GOTO: printf("%s\t%d\tGOTO\n", name, line); break;
                                case IF: printf("%s\t%d\tIF\n", name, line); break;
                                case INLINE: printf("%s\t%d\tINLINE\n", name, line); break;
                                case INT: printf("%s\t%d\tINT\n", name, line); break;
                                case LONG: printf("%s\t%d\tLONG\n", name, line); break;
                                case REGISTER: printf("%s\t%d\tREGISTER\n", name, line); break;
                                case RESTRICT: printf("%s\t%d\tRESTRICT\n", name, line); break;
                                case RETURN: printf("%s\t%d\tRETURN\n", name, line); break;
                                case SHORT: printf("%s\t%d\tSHORT\n", name, line); break;
                                case SIGNED: printf("%s\t%d\tSIGNED\n", name, line); break;
                                case SIZEOF: printf("%s\t%d\tSIZEOF\n", name, line); break;
                                case STATIC: printf("%s\t%d\tSTATIC\n", name, line); break;
                                case STRUCT: printf("%s\t%d\tSTRUCT\n", name, line); break;
                                case SWITCH: printf("%s\t%d\tSWITCH\n", name, line); break;
                                case TYPEDEF: printf("%s\t%d\tTYPEDEF\n", name, line); break;
                                case UNION: printf("%s\t%d\tUNION\n", name, line); break;
                                case UNSIGNED: printf("%s\t%d\tUNSIGNED\n",name,line); break;
                                case VOID: printf("%s\t%d\tUNION\n", name, line); break;
                                case VOLATILE: printf("%s\t%d\tVolatile\n", name, line); break;
                                case WHILE: printf("%s\t%d\tWHILE\n", name, line);break;
                                case _BOOL: printf("%s\t%d\t_BOOL\n", name, line); break;
                                case _COMPLEX: printf("%s\t%d\t_COMPLEX\n", name, line); break;
                                case _IMAGINARY: printf("%s\t%d\t_IMAGINARY\n",name,line); break;
                        }

        }
        free(yylval);



}

