
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* Feature test macros. Flex uses functions that require a minimum set of
 * macros defined. As defining some macros may hide function declarations that
 * user code might use, be conservative and respect user's definitions as much
 * as possible. In glibc, feature test macros may not be all set up until one
 * of the libc header (that includes <features.h>) is included. This creates
 * a circular dependency when we check the macros. <assert.h> is the safest
 * header we can include and does not declare too many functions we don't need.
 */
#if !defined(__GNU_LIBRARY__) && defined(__STDC__)
#include <assert.h>
#endif
#if !(defined(_POSIX_C_SOURCE) || defined(_XOPEN_SOURCE) || \
    defined(_POSIX_SOURCE))
# define _POSIX_C_SOURCE 1 /* Required for fileno() */
# define _POSIX_SOURCE 1
#endif
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C++ systems might need __STDC_LIMIT_MACROS defined before including
 * <stdint.h>, if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[329] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   90,   88,
       85,   86,    5,    1,   86,   86,   86,    6,   86,   86,
       86,   27,   86,   24,   21,   86,   86,   86,   87,   87,
       86,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   86,   11,   89,
       14,   89,   12,   13,    3,    4,    3,   34,   40,   35,
       46,   38,   29,   41,   30,   42,   15,    0,   27,   27,
        0,    0,   39,   27,   24,    0,   24,   24,   25,    0,
        0,    0,   25,   21,   21,   22,    0,    0,   22,   16,
       31,   33,   32,   17,   87,    5,    6,   47,   87,   87,

       87,   87,   87,   87,   87,   87,   87,   55,   87,   87,
       87,   87,   87,   87,   63,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   45,   36,   11,    7,
        8,    9,    8,    0,    7,   12,    0,    2,    0,   37,
        0,   27,    0,   27,   27,   25,   26,   25,   18,    0,
       28,    0,   28,   25,   22,   23,   22,    0,   21,    0,
       21,   22,   43,   44,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   61,   87,
       87,   65,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,    9,   10,

       27,   27,   27,   27,   25,   18,   19,    0,   19,   28,
       28,   28,   28,   28,   25,   22,   21,   21,   21,   21,
       21,   22,   87,   87,   87,   48,   87,   50,   51,   87,
       87,   87,   87,   57,   58,   87,   87,   62,   87,   66,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   79,   87,   87,    9,   19,   20,   19,    0,
       18,   19,   82,   87,   87,   49,   52,   87,   87,   87,
       87,   60,   87,   87,   87,   87,   70,   87,   87,   87,
       87,   87,   87,   77,   87,   87,   81,   19,   18,   18,
       19,   87,   87,   87,   87,   56,   59,   64,   87,   87,

       69,   71,   72,   73,   74,   75,   87,   87,   87,   87,
       87,   87,   54,   87,   87,   76,   87,   87,   83,   87,
       53,   67,   68,   78,   80,   87,   84,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    5,    6,    7,    8,    9,   10,    7,
        7,   11,   12,    7,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   18,   18,    7,    7,   19,
       20,   21,   22,    7,   23,   24,   25,   23,   23,   26,
       27,   27,   28,   27,   27,   29,   27,   27,   27,   27,
       27,   27,   27,   27,   30,   27,   27,   31,   27,   27,
        7,   32,    7,   33,   34,    7,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   27,   44,   45,   46,   47,
       48,   49,   27,   50,   51,   52,   53,   54,   55,   56,
       57,   58,    7,   59,    7,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    2,    2,    1,    2,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    4,    4,    4,    1,    1,
        1,    1,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    2,    1,    5,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    3
    } ;

static const flex_int16_t yy_base[338] =
    {   0,
        0,    0,   58,   62,   66,   70,   74,   78,  647,  648,
      648,  626,  648,  648,  648,  625,   65,  648,  624,   50,
       71,  116,  623,  162,  208,   67,  622,   68,    0,   90,
      621,   79,  587,  589,   64,   57,   63,   66,  590,   69,
      589,  597,   84,  578,  587,  585,  590,   58,    0,  648,
      648,  263,    0,  648,  648,  648,   61,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  617,  616,  648,
      131,  134,  648,  104,   82,  146,  648,  124,  112,    0,
      155,  169,  160,    0,  187,  155,  186,  216,  206,  602,
      648,  648,  648,  601,    0,  648,  648,  648,  568,  548,

      549,  542,  553,  539,  554,  541,  546,  532,  533,  529,
      529,  532,  528,  525,    0,   79,  528,  179,  526,   82,
       47,  530,  523,  107,   92,  528,  648,  648,    0,  648,
      180,  192,  648,    0,  648,    0,   96,  648,  566,  648,
      224,  246,  226,  271,    0,  197,  648,  210,  278,  231,
      316,  253,  322,  291,  224,  648,  231,  264,  337,  275,
      352,  330,  648,  648,  518,  519,  526,  512,  524,  518,
      499,  250,  513,  509,  505,  495,  501,  501,    0,  480,
      483,    0,  484,  480,  468,  459,  461,  457,  461,  447,
      445,  445,  453,  439,  443,  446,  448,  432,  308,    0,

      369,  384,  390,  405,  648,  335,  267,  420,  410,  430,
      436,  648,  456,  462,  648,  648,  477,  492,  648,  498,
      513,  648,  426,  419,  426,    0,  422,    0,    0,  409,
      417,  405,  412,    0,    0,  401,  392,    0,  395,    0,
      390,  386,  377,  374,  386,  372,  375,  380,  378,  374,
      364,  364,    0,  352,  364,  648,  276,  648,  312,  329,
      517,  460,    0,  354,  353,    0,    0,  346,  346,  351,
      337,    0,  340,  324,  331,  326,    0,  334,  318,  315,
      297,  301,  289,    0,  271,  271,    0,  648,  534,  538,
      648,  270,  257,  241,  232,    0,    0,    0,  239,  237,

        0,    0,    0,    0,    0,    0,  226,  219,  207,  189,
      188,  173,    0,  160,  154,    0,  156,  135,    0,  120,
        0,    0,    0,    0,    0,  109,    0,  648,  597,  602,
      607,  609,  614,  619,  624,  155,  111
    } ;

static const flex_int16_t yy_def[338] =
    {   0,
      328,    1,  329,  329,  330,  330,  331,  331,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  332,  332,
      328,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  328,  333,  328,
      328,  328,  334,  328,  328,  328,  335,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,   22,  328,
      328,  328,  328,   22,   24,  328,  328,  328,  328,  336,
      328,  328,  328,   25,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  332,  328,  328,  328,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  328,  328,  333,  328,
      328,  328,  328,  337,  328,  334,  335,  328,  335,  328,
      328,  328,  328,  328,   74,  328,  328,  328,  336,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  328,  337,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  328,  328,  328,  328,  328,
      328,  328,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  328,  328,  328,
      328,  332,  332,  332,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,    0,  328,  328,
      328,  328,  328,  328,  328,  328,  328
    } ;

static const flex_int16_t yy_nxt[708] =
    {   0,
       10,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   25,   26,   27,
       28,   15,   29,   29,   29,   29,   29,   29,   30,   29,
       29,   15,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   29,   40,   29,   41,   29,   29,   29,   29,   42,
       43,   44,   45,   46,   47,   29,   29,   29,   48,   50,
       50,   63,   51,   50,   50,  138,   51,   50,   50,   64,
       50,   50,   50,   60,   50,   54,   56,  127,   57,   54,
       56,  190,   57,   65,   61,   90,   91,   93,   94,   52,
       66,   67,  139,   52,   96,  107,  191,   52,  104,   97,

      138,   52,   99,  100,  108,  105,  101,  109,  115,  110,
      112,  106,  328,  113,  200,  116,  128,  328,  111,  145,
      145,  145,  188,  181,   50,  119,  120,  139,   50,   68,
      182,   69,   69,   69,  196,  121,  197,  328,  122,  189,
      148,   70,  141,  141,   70,  143,  143,  142,  142,  194,
      144,  144,  146,  147,   71,   70,  148,  195,  149,   74,
       70,   76,   76,   76,   72,  327,  150,  150,  146,  326,
      148,  151,  151,  325,   70,   74,  147,   75,   75,   76,
      152,  152,  146,  157,   81,  153,  153,   77,  154,  147,
       78,   79,   80,  324,   82,  199,  199,  158,  158,  157,

       81,   77,  159,  159,  154,  323,   78,  199,  199,  322,
       82,  321,  147,  157,   79,  155,  156,   80,  154,  184,
       83,   74,  320,   84,   84,   84,  147,  160,  160,  185,
      186,  155,  161,  161,  162,  156,   85,   86,  205,  156,
      142,  142,  144,  144,  319,  155,   87,  151,  151,  147,
      162,  318,   85,  156,  205,  147,   88,  317,  156,  216,
       86,  201,  202,  202,  162,  316,   89,  130,  205,  153,
      153,   70,  130,  315,   70,  216,  156,  314,  131,  132,
      159,  159,  156,  313,  130,   70,  203,  204,  204,  216,
       70,  161,  161,  312,  130,  259,   70,  133,  133,   70,

      230,  231,  133,  311,   70,  258,  206,  207,  310,  133,
       70,  259,  133,  309,  133,   70,  133,  308,  134,  205,
      147,  135,  206,  256,  256,  259,  208,  307,  258,   70,
      207,  210,  211,  211,  258,  205,  209,  213,  214,  214,
      288,  212,  306,  147,  212,  261,  261,  212,  305,  215,
      212,  304,  217,  218,  218,  212,  288,  303,  216,  156,
      212,  212,  212,  257,  258,  219,  212,  220,  221,  221,
      288,  302,  301,  300,  216,  299,  212,  212,  298,  257,
      219,  219,  156,  297,  201,  202,  202,  258,  222,  296,
      295,  212,  294,  257,   70,  293,  219,   70,  292,  201,

      202,  202,  287,  286,  285,  203,  204,  204,   70,   70,
      284,  283,   70,   70,  282,   70,  281,  280,   70,  279,
      203,  204,  204,   70,  278,  277,  276,   70,   70,   70,
       70,  260,  260,   70,   70,  275,  261,  261,  262,  258,
      274,  273,   70,  272,   70,  210,  211,  211,   70,   70,
      271,  210,  211,  211,  262,  212,  270,  269,  212,  268,
      267,  212,  258,   70,  212,  266,  265,  264,  262,  212,
      263,  213,  214,  214,  212,  212,  255,  213,  214,  214,
      212,  212,  254,  253,  212,  252,  251,  212,  288,  258,
      212,  250,  217,  218,  218,  212,  249,  248,  247,  246,

      212,  212,  212,  245,  288,  219,  212,  217,  218,  218,
      244,  243,  258,  220,  221,  221,  212,  212,  291,  242,
      219,  219,  241,  212,  240,  239,  219,  238,  220,  221,
      221,  212,  289,  290,  290,  237,  219,  212,  212,  236,
      235,  219,  219,  234,  233,  206,  207,  232,  229,  289,
      290,  290,  212,  289,  290,  290,  228,  219,  227,  226,
      225,  206,  206,  207,  224,  223,  206,  207,  328,  207,
      198,  193,  192,  187,  183,  209,  180,  179,  206,  178,
      177,  176,  206,  175,  174,  173,  207,  172,  171,  170,
      207,  169,  209,  168,  167,  166,  209,   49,   49,   49,

       49,   49,   53,   53,   53,   53,   53,   55,   55,   55,
       55,   55,   95,   95,  129,  165,  129,  129,  129,  136,
      164,  163,  136,  136,  137,  137,  137,  137,  137,  328,
      140,  126,  125,  124,  123,  118,  117,  114,  103,  102,
       98,   92,   73,   62,   59,   58,  328,    9,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328
    } ;

static const flex_int16_t yy_chk[708] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,   20,    3,    4,    4,   57,    4,    5,    5,   20,
        5,    6,    6,   17,    6,    5,    7,   48,    7,    6,
        8,  121,    8,   21,   17,   26,   26,   28,   28,    3,
       21,   21,   57,    4,   30,   36,  121,    5,   35,   30,

      137,    6,   32,   32,   36,   35,   32,   37,   40,   37,
       38,   35,   75,   38,  337,   40,   48,   74,   37,   74,
       74,   74,  120,  116,    5,   43,   43,  137,    6,   22,
      116,   22,   22,   22,  125,   43,  125,   75,   43,  120,
       79,   22,   71,   71,   22,   72,   72,   71,   71,  124,
       72,   72,   78,   78,   22,   22,   79,  124,  336,   76,
       22,   76,   76,   76,   22,  326,   81,   81,   78,  320,
       79,   81,   81,  318,   22,   24,   78,   24,   24,   24,
       82,   82,   78,   86,   76,   82,   82,   24,   83,   83,
       24,   24,   24,  317,   76,  131,  131,   87,   87,   86,

       24,   24,   87,   87,   83,  315,   24,  132,  132,  314,
       24,  312,   83,   86,   24,   85,   85,   24,   83,  118,
       24,   25,  311,   25,   25,   25,  146,   88,   88,  118,
      118,   85,   88,   88,   89,   89,   25,   25,  148,   85,
      141,  141,  143,  143,  310,   85,   25,  150,  150,  146,
       89,  309,   25,  155,  148,  146,   25,  308,   89,  157,
       25,  142,  142,  142,   89,  307,   25,   52,  148,  152,
      152,  142,   52,  300,  142,  157,  155,  299,   52,   52,
      158,  158,  155,  295,   52,  142,  144,  144,  144,  157,
      142,  160,  160,  294,   52,  207,  144,   52,   52,  144,

      172,  172,   52,  293,  142,  257,  149,  149,  292,   52,
      144,  207,   52,  286,   52,  144,   52,  285,   52,  154,
      154,   52,  149,  199,  199,  207,  149,  283,  257,  144,
      149,  151,  151,  151,  257,  154,  149,  153,  153,  153,
      259,  151,  282,  154,  151,  260,  260,  153,  281,  154,
      153,  280,  159,  159,  159,  151,  259,  279,  162,  162,
      151,  153,  159,  206,  206,  159,  153,  161,  161,  161,
      259,  278,  276,  275,  162,  274,  159,  161,  273,  206,
      161,  159,  162,  271,  201,  201,  201,  206,  162,  270,
      269,  161,  268,  206,  201,  265,  161,  201,  264,  202,

      202,  202,  255,  254,  252,  203,  203,  203,  201,  202,
      251,  250,  202,  201,  249,  203,  248,  247,  203,  246,
      204,  204,  204,  202,  245,  244,  243,  201,  202,  203,
      204,  208,  208,  204,  203,  242,  208,  208,  209,  209,
      241,  239,  202,  237,  204,  210,  210,  210,  203,  204,
      236,  211,  211,  211,  209,  210,  233,  232,  210,  231,
      230,  211,  209,  204,  211,  227,  225,  224,  209,  210,
      223,  213,  213,  213,  210,  211,  198,  214,  214,  214,
      211,  213,  197,  196,  213,  195,  194,  214,  262,  262,
      214,  193,  217,  217,  217,  213,  192,  191,  190,  189,

      213,  214,  217,  188,  262,  217,  214,  218,  218,  218,
      187,  186,  262,  220,  220,  220,  217,  218,  262,  185,
      218,  217,  184,  220,  183,  181,  220,  180,  221,  221,
      221,  218,  261,  261,  261,  178,  218,  220,  221,  177,
      176,  221,  220,  175,  174,  261,  261,  173,  171,  289,
      289,  289,  221,  290,  290,  290,  170,  221,  169,  168,
      167,  261,  289,  289,  166,  165,  290,  290,  139,  261,
      126,  123,  122,  119,  117,  261,  114,  113,  289,  112,
      111,  110,  290,  109,  108,  107,  289,  106,  105,  104,
      290,  103,  289,  102,  101,  100,  290,  329,  329,  329,

      329,  329,  330,  330,  330,  330,  330,  331,  331,  331,
      331,  331,  332,  332,  333,   99,  333,  333,  333,  334,
       94,   90,  334,  334,  335,  335,  335,  335,  335,   69,
       68,   47,   46,   45,   44,   42,   41,   39,   34,   33,
       31,   27,   23,   19,   16,   12,    9,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parseLex.l"
#line 3 "parseLex.l"



#include "parser.tab.h"
#include <stdio.h>
#include <math.h>
#include <ctype.h>
#include <string.h>
#define INTLONG 500
#define LLU 501
#define newline 600
#define PUNCTUATION 601

char* placeholder;
char name[1024] = "stdin";
int isFloat=0;
int line = 1;
#line 743 "lex.yy.c"
 
#line 745 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define CHAR 2
#define FILEINFO 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 35 "parseLex.l"

#line 967 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 329 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 648 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "parseLex.l"
{BEGIN(FILEINFO);}
	YY_BREAK
/*<FILEINFO>[0-9]+    { line = (int) strtol (yytext,NULL, 10); }*/
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 39 "parseLex.l"
{      
                strncpy(name, yytext+1, strlen(yytext)-2); //copy into filename
                name[strlen(yytext)-2] = '\0'; //ignore ""
                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "parseLex.l"
{ ;}  
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 45 "parseLex.l"
{BEGIN(INITIAL);}
	YY_BREAK
/*[a-z|A-Z]+\.c   {yylval.string = strdup(yytext);name = yylval.string; return NAME;*/
case 5:
YY_RULE_SETUP
#line 47 "parseLex.l"
{BEGIN(STRING);placeholder= malloc(sizeof(char));sprintf(placeholder,"");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "parseLex.l"
{BEGIN(CHAR);placeholder= malloc(sizeof(char));sprintf(placeholder,"");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "parseLex.l"
{strcat(placeholder,&yytext[1]);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "parseLex.l"
{strcat(placeholder, yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "parseLex.l"
{long temp = strtol(yytext+1,NULL,8);char* storage=malloc(sizeof(char));
        if(temp > 255){
                
                fprintf(stderr,"%s:%d:Hex escape sequence %s out of range",name,line); 
                temp = 255;
        }
        int intTemp = temp;
        if(isprint(temp)==0){
                sprintf(storage,"\\%03o",intTemp);
        }
        else{
                sprintf(storage,"%c",intTemp);
        }
        strcat(placeholder,storage);free(storage);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "parseLex.l"
{long temp = strtol(yytext+2,NULL,16);char* storage=malloc(sizeof(char));
        if(temp > 255){
                fprintf(stderr,"%s:%d:Hex escape sequence %s out of range",name,line); 
                temp = 255;
        }
        int intTemp = temp;
        if(isprint(temp)==0){
                sprintf(storage,"\\%03o",intTemp);
        }
        else{
                sprintf(storage,"%c",intTemp);
        }
        strcat(placeholder,storage);free(storage);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "parseLex.l"
{strcat(placeholder, yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 81 "parseLex.l"
{strcat(placeholder, yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 82 "parseLex.l"
{BEGIN(INITIAL);
        if(strlen(placeholder) >1){
                fprintf(stderr,"%s:%d:WARNING:Unsupported multibyte character literal truncated to first byte \n",name,line); 
                placeholder[1] = '\0';
        }
        yylval.number.type = 9;
        yylval.number.value.charVal= placeholder[0]; 
        free(placeholder);
        return CHAR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 91 "parseLex.l"
{BEGIN(INITIAL);yylval.string = strdup(placeholder); free(placeholder);return newString;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 93 "parseLex.l"
{return INDSEL;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 94 "parseLex.l"
{return SHL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 95 "parseLex.l"
{return SHR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 96 "parseLex.l"
{
        char * end;
        long temp = strtol(yytext+2,&end,16);
        char* storage= malloc(sizeof(char));
        sprintf(storage,"%ld",temp);
        strcat(storage,end);yylval.string =strdup(storage);
        free(storage);
        isFloat = numberProcessing(0);
        
        
        

        return NUMBER;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 109 "parseLex.l"
{
        char * end;
        long temp = strtol(yytext+2,&end,16);
        char* storage= malloc(sizeof(char));
        sprintf(storage,"%ld",temp);
        strcat(storage,end);yylval.string =strdup(storage);
        free(storage);
        isFloat = numberProcessing(0);
        
        
        

        return NUMBER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "parseLex.l"
{
        char * end;
        long temp = strtol(yytext+2,&end,16);
        char* storage= malloc(sizeof(char));
        sprintf(storage,"%ld",temp);
        strcat(storage,end);yylval.string =strdup(storage);
        free(storage);
        isFloat = numberProcessing(0);
        
        
        

        return NUMBER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 135 "parseLex.l"
{
        yylval.string = strdup(yytext);
        isFloat  = numberProcessing(0);
        return NUMBER;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 140 "parseLex.l"
{        
        yylval.string = strdup(yytext);
        isFloat  = numberProcessing(0);
        return NUMBER;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 145 "parseLex.l"
{
        yylval.string = strdup(yytext);
        isFloat  = numberProcessing(0);
        return NUMBER;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 150 "parseLex.l"
{
        char * end;
        long temp = strtol(yytext,&end,8);
        char* storage= malloc(1024);
        sprintf(storage,"%ld",temp);
        strcat(storage,end);
        yylval.string =strdup(storage);

        free(storage);
        isFloat = numberProcessing(isFloat);
        return NUMBER;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 161 "parseLex.l"
{
        char * end;
        long temp = strtol(yytext,&end,8);
        char* storage= malloc(1024);
        sprintf(storage,"%ld",temp);
        strcat(storage,end);
        yylval.string =strdup(storage);

        free(storage);
        isFloat = numberProcessing(isFloat);
        return NUMBER;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 172 "parseLex.l"
{
        char * end;
        long temp = strtol(yytext,&end,8);
        char* storage= malloc(1024);
        sprintf(storage,"%ld",temp);
        strcat(storage,end);
        yylval.string =strdup(storage);

        free(storage);
        isFloat = numberProcessing(isFloat);
        return NUMBER;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 183 "parseLex.l"
{
        
        yylval.string = strdup(yytext);
        isFloat = 1; 
        isFloat = numberProcessing(isFloat);
        return NUMBER; }  
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 189 "parseLex.l"
{
        yylval.string = strdup(yytext);
        isFloat  = numberProcessing(0);
        return NUMBER;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 194 "parseLex.l"
{return PLUSPLUS;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 195 "parseLex.l"
{return MINUSMINUS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 196 "parseLex.l"
{return LTEQ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 197 "parseLex.l"
{return GTEQ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 198 "parseLex.l"
{return EQEQ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 199 "parseLex.l"
{return NOTEQ;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 200 "parseLex.l"
{return LOGAND;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 201 "parseLex.l"
{return LOGOR;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 202 "parseLex.l"
{return ELLIPSIS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 203 "parseLex.l"
{return TIMESEQ;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 204 "parseLex.l"
{return DIVEQ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 205 "parseLex.l"
{return MODEQ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 206 "parseLex.l"
{return PLUSEQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 207 "parseLex.l"
{return MINUSEQ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 208 "parseLex.l"
{return SHLEQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 209 "parseLex.l"
{return SHREQ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 210 "parseLex.l"
{return OREQ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 211 "parseLex.l"
{return ANDEQ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 212 "parseLex.l"
{return XOREQ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 213 "parseLex.l"
{return AUTO;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 214 "parseLex.l"
{return BREAK;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 215 "parseLex.l"
{return CASE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 216 "parseLex.l"
{return CHAR;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 217 "parseLex.l"
{return CONST;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 218 "parseLex.l"
{return CONTINUE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 219 "parseLex.l"
{return DEFAULT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 220 "parseLex.l"
{return DO;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 221 "parseLex.l"
{return DOUBLE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 222 "parseLex.l"
{return ELSE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 223 "parseLex.l"
{return ENUM;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 224 "parseLex.l"
{return EXTERN;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 225 "parseLex.l"
{return FLOAT;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 226 "parseLex.l"
{return FOR;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 227 "parseLex.l"
{return GOTO;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 228 "parseLex.l"
{return IF;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 229 "parseLex.l"
{return INLINE;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 230 "parseLex.l"
{return INT;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 231 "parseLex.l"
{return LONG;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 232 "parseLex.l"
{return REGISTER;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 233 "parseLex.l"
{return RESTRICT;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 234 "parseLex.l"
{return RETURN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 235 "parseLex.l"
{return SHORT;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 236 "parseLex.l"
{return SIGNED;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 237 "parseLex.l"
{return SIZEOF;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 238 "parseLex.l"
{return STATIC;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 239 "parseLex.l"
{return STRUCT;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 240 "parseLex.l"
{return SWITCH;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 241 "parseLex.l"
{return TYPEDEF;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 242 "parseLex.l"
{return UNION;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 243 "parseLex.l"
{return UNSIGNED;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 244 "parseLex.l"
{return VOID;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 245 "parseLex.l"
{return VOLATILE;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 246 "parseLex.l"
{return WHILE;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 247 "parseLex.l"
{return _BOOL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 248 "parseLex.l"
{return _COMPLEX;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 249 "parseLex.l"
{return _IMAGINARY;}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 250 "parseLex.l"
{line = line + 1;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 251 "parseLex.l"
{
        
        yylval.string = strdup(yytext);
       // printf("String is %s\n", yylval.string);
        int returnVal = yylval.string[0];
       // printf("Punctuation is %i\n", returnVal);
        return returnVal;
        }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 259 "parseLex.l"
{yylval.string = strdup(yytext);return IDENT;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 260 "parseLex.l"
{fprintf(stderr, "Error: Unknown token %s\n", yytext);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 262 "parseLex.l"
ECHO;
	YY_BREAK
#line 1604 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(FILEINFO):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 329 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 329 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 328);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 262 "parseLex.l"




int numberProcessing(int realCheck){
        int isFloat = realCheck;
        double floatVal;
        char* copyVal;
        
        int charCount =0;
        long eSign = 0;
        long eVal = 0;
        int pSign =0;
        int pVal =0;
        char* type = malloc(1024);
        sprintf(type,"");
        char* end;
        char* eCheck = NULL;
        char* pCheck = NULL;
        char* fCheck = NULL;
        char* temp = strdup(yylval.string);
        if(strchr(yylval.string,'f') != NULL){
                fCheck = strchr(yylval.string,'f');
                
        }
        else if (strchr(yylval.string,'F') != NULL){
                fCheck = strchr(yylval.string,'F');
                
        }
        if(strchr(yylval.string,'e') != NULL){
                eCheck = strchr(yylval.string,'e');
        }
        else if (strchr(yylval.string,'E') != NULL){
                eCheck = strchr(yylval.string,'E');
        }
        
        if(strchr(yylval.string,'p') != NULL){
                pCheck = strchr(yylval.string,'p');
        }
        else if(strchr(yylval.string,'P') != NULL){
                pCheck = strchr(yylval.string,'P');
        }
        
        
        if ( eCheck!= NULL){
                isFloat = 1;
                charCount+=1;
                
                if(isdigit(eCheck[1])){
                        eSign = 1;
                        eVal = strtol(yylval.string+(int)(eCheck-yylval.string)+1,NULL,10);
                }
                else if (eCheck[1] == '-'){
                        charCount+=1;
                        eSign = -1;
                        eVal = strtol(yylval.string+(int)(eCheck-yylval.string)+2,NULL,10);
                }
                else{
                        charCount+=1;
                        eSign = 1;
                        eVal = strtol(yylval.string+(int)(eCheck-yylval.string)+2,NULL,10);
                }
                
                
                
        }

        long test = eVal;
        while (test>0){
                test = test/10;
                charCount++;
        }
        if ( pCheck!= NULL){
                isFloat = 1;
                charCount+=1;
                
                if(isdigit(pCheck[1])){
                        pSign = 1;
                        pVal = strtol(temp+(int)(pCheck-temp)+1,NULL,10);
                }
                else if (pCheck[1] == '-'){
                        charCount+=1;
                        pSign = -1;
                        pVal = strtol(yylval.string+(int)(pCheck-yylval.string)+2,NULL,10);
                }
                else{
                        charCount+=1;
                        pSign = 1;
                        pVal = strtol(yylval.string+(int)(pCheck-yylval.string)+2,NULL,10);
                }
                
                
                
        }

        test = pVal;
        while (test>0){
                test = test/10;
                charCount++;
        }
        if(!isFloat){
                
                if((strchr(temp,'U') != NULL) || (strchr(temp,'u') != NULL))
                {
                        yylval.number.type = 1;
                        
                        charCount++;
                }
                if(strstr(temp,"LL") != NULL)
                {       if(yylval.number.type == 1){
                                yylval.number.type = 4;
                        }
                        else{
                                yylval.number.type = 5;
                        }
                        
                        charCount+=2;

                }
                else if(strstr(temp,"L") != NULL || strstr(temp,"l") != NULL)
                {       if(yylval.number.type == 1){
                                yylval.number.type = 3;
                        }
                        else{
                                yylval.number.type = 2;
                        }

                        
                        charCount++;

                }
                else {
                        yylval.number.type = 0;
                        
                }

                
                
        }
        
        
        if(isFloat){
                
                if( (strchr(temp,'L') != NULL) || (strchr(temp,'l') != NULL))
                {
                        yylval.number.type = 8;
                        
                        charCount++;

                }
                else if(strchr(temp,'f')!= NULL || strchr(temp,'F')!= NULL  ){
                        yylval.number.type = 7;
                        
                        charCount++;
                }
                else{
                        yylval.number.type = 6;
                        
                }
                
                
                
        }
        if(charCount!=0){
                temp[strlen(temp)-charCount] = '\0';
        }
        floatVal = atof(temp);
        long double numTemp = floatVal * pow(10,eSign*eVal) * pow(2,pSign*pVal);
        if(isFloat){
                yylval.number.value.realVal = numTemp;
        }
        else{
                yylval.number.value.intVal= numTemp;
        }
        
        //sprintf(yylval.string,"%Lg\t%s",temp,type);
        free(type);
        return isFloat;

        
}

