
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* Feature test macros. Flex uses functions that require a minimum set of
 * macros defined. As defining some macros may hide function declarations that
 * user code might use, be conservative and respect user's definitions as much
 * as possible. In glibc, feature test macros may not be all set up until one
 * of the libc header (that includes <features.h>) is included. This creates
 * a circular dependency when we check the macros. <assert.h> is the safest
 * header we can include and does not declare too many functions we don't need.
 */
#if !defined(__GNU_LIBRARY__) && defined(__STDC__)
#include <assert.h>
#endif
#if !(defined(_POSIX_C_SOURCE) || defined(_XOPEN_SOURCE) || \
    defined(_POSIX_SOURCE))
# define _POSIX_C_SOURCE 1 /* Required for fileno() */
# define _POSIX_SOURCE 1
#endif
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C++ systems might need __STDC_LIMIT_MACROS defined before including
 * <stdint.h>, if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[262] =
    {   0,
        0,    0,    0,    0,    0,    0,   77,   75,   72,   73,
        2,   73,   73,   73,    3,   73,   73,   73,   73,   73,
       15,   14,   73,   75,   73,   74,   73,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   73,    8,   76,    9,   76,   21,   27,
       22,   33,   25,   16,   28,   17,   29,   10,    0,   26,
       15,   15,   15,    0,   15,   14,   14,   14,   14,   11,
       18,   20,   19,   12,    0,   74,   74,   34,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   42,   74,   74,
       74,   74,   74,   74,   50,   74,   74,   74,   74,   74,

       74,   74,   74,   74,   74,   74,   32,   23,    8,    4,
        5,    6,    5,    0,   24,   15,   15,   13,   13,   14,
       30,   31,    1,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   48,   74,   74,
       52,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,    6,    7,   13,
       13,   13,   13,   13,   74,   74,   74,   35,   74,   37,
       38,   74,   74,   74,   74,   44,   45,   74,   74,   49,
       74,   53,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   66,   74,   74,    6,   13,   69,

       74,   74,   36,   39,   74,   74,   74,   74,   47,   74,
       74,   74,   74,   57,   74,   74,   74,   74,   74,   74,
       64,   74,   74,   68,   74,   74,   74,   74,   43,   46,
       51,   74,   74,   56,   58,   59,   60,   61,   62,   74,
       74,   74,   74,   74,   74,   41,   74,   74,   63,   74,
       74,   70,   74,   40,   54,   55,   65,   67,   74,   71,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    5,    6,    6,    7,    8,    9,    6,
        6,   10,   11,    6,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   17,   17,    6,    6,   18,
       19,   20,   21,    6,   22,   23,   24,   22,   22,   22,
       25,   25,   26,   25,   25,   27,   25,   25,   25,   25,
       25,   25,   25,   25,   28,   25,   25,   29,   25,   25,
        6,   30,    6,   31,   32,    6,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   25,   42,   43,   44,   45,
       46,   47,   25,   48,   49,   50,   51,   52,   53,   54,
       55,   56,    6,   57,    6,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    2,    2,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    4,    4,    4,    1,    1,    1,
        1,    4,    4,    4,    5,    5,    5,    5,    5,    2,
        1,    5,    4,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    4
    } ;

static const flex_int16_t yy_base[268] =
    {   0,
        0,    0,   56,   60,   64,   68,  245,  950,  950,  219,
      950,  950,  218,   56,  950,  211,   49,   60,  207,  200,
       84,   80,   58,  198,   62,   72,  197,   79,  101,  113,
      127,  116,  125,  141,  117,  145,  136,  155,  153,  156,
      164,  167,  172,  189,    0,  950,  950,  242,  950,  950,
      950,  950,  950,  950,  950,  950,  950,  950,  185,  950,
      199,   79,   82,    0,  196,  216,  197,  198,  209,  161,
      950,  950,  950,  158,  140,    0,  188,  950,  126,  120,
      120,  228,  249,  251,  231,  265,  268,  269,  279,  283,
      291,  293,  302,  303,  305,  314,  322,  326,  323,  338,

      340,  341,  350,  352,  362,  366,  950,  371,    0,  950,
       68,   76,  950,    0,  950,  222,  950,  382,  261,  950,
      950,  950,  950,  109,  110,  118,  380,  381,  382,  383,
      397,  402,  411,  416,  419,  421,  431,  433,  435,  443,
      445,  447,  455,  457,  459,  469,  473,  483,  481,  492,
      495,  493,  504,  507,  516,  518,  526,  104,    0,  455,
      527,    0,  528,    0,  105,  100,  107,  527,  535,  543,
      546,  547,  555,  558,  567,  566,  575,  578,  583,  592,
      594,  595,  597,  609,  612,  621,  626,  629,  637,  641,
      649,  652,  657,  640,  660,  661,  672,  950,  950,    0,

       91,   91,  675,  677,  680,  689,  691,  694,  703,  705,
      708,  719,  717,  728,  731,  740,  748,  739,  736,  758,
      757,  760,  768,  777,   87,   76,  778,  780,  779,  782,
      794,  798,  806,  803,  814,  815,  817,  818,  826,  829,
      837,  838,   61,   77,  849,  847,  852,  857,  866,  868,
      876,    0,   53,  877,  878,  886,  887,  888,   38,    0,
      950,  934,  937,  939,  944,   74,   70
    } ;

static const flex_int16_t yy_def[268] =
    {   0,
      261,    1,  262,  262,  262,  262,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  263,  261,  264,  263,  263,
      263,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,  265,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  266,  266,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  264,   31,  261,  264,  264,
      264,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   31,   31,  261,   31,  265,  261,
      261,  261,  261,  267,  261,  261,  261,  266,  118,  261,
      261,  261,  261,  264,  264,  264,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,  261,  267,  261,
      261,  118,  261,  118,  264,  264,  264,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,  261,  261,  264,

      264,  264,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,  264,  264,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,  264,  264,   31,   31,   31,   31,   31,   31,
       31,  264,  264,   31,   31,   31,   31,   31,  264,  264,
        0,  261,  261,  261,  261,  261,  261
    } ;

static const flex_int16_t yy_nxt[1008] =
    {   0,
        8,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   22,   23,   24,   25,
       12,   26,   26,   26,   26,   26,   26,   26,   26,   12,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   26,
       36,   26,   37,   26,   26,   26,   26,   38,   39,   40,
       41,   42,   43,   26,   26,   26,   44,   46,   46,   54,
       47,   46,   46,   51,   47,   46,   46,   55,   46,   46,
       46,   56,   46,  159,   52,   70,   71,  118,   57,   58,
       73,   74,  158,  158,   75,   48,   76,   76,   76,   48,
      158,  158,  260,   48,   66,   66,   66,   48,   61,   61,

      259,   79,   80,   76,   81,  117,   67,   68,   62,  253,
       62,   63,   64,   75,  252,   76,   76,   76,  198,  198,
      244,  117,   67,  243,   62,   75,   62,   76,   76,   76,
       68,  226,   76,  225,   63,  117,   69,   64,   62,   75,
       65,   76,   76,   76,   76,  202,  201,  200,   77,   77,
      167,   82,   87,  166,  165,   77,   77,   77,   76,   84,
       83,   88,   94,  126,   77,  125,   85,   89,   77,   90,
       77,  124,   86,   77,  123,   77,  122,   77,   91,  121,
       77,   97,   95,   92,   77,   77,   93,   77,   77,   96,
       77,   98,   99,  100,   77,   77,   77,  115,   77,   77,

       77,   77,  101,   77,   77,  102,   77,  107,  104,   77,
      103,  106,  105,   61,   61,   78,   72,   77,   60,   59,
       77,   77,   62,  120,   67,   62,   63,   77,   77,   53,
       66,   66,   66,   77,   77,   67,   50,   49,   62,  120,
       67,   62,   67,   68,  261,  108,  110,  261,   62,   63,
      110,   67,  119,  120,   67,  116,  111,  112,   67,  261,
       77,  261,  110,  130,   62,   67,   68,   77,  261,  261,
       77,  110,   69,   77,  113,  113,   77,  127,   62,  113,
      261,   77,  261,   77,  261,  128,  113,  163,   77,  113,
       77,  113,  261,  113,   77,  114,   77,   77,  113,  129,

       77,   77,  261,  163,   77,  132,  261,   77,   77,  131,
       77,   77,  261,   77,   77,   77,  261,  164,   77,  133,
      261,  261,   77,   77,   77,   77,  261,  134,   77,  261,
       77,  261,   77,  135,   77,   77,   77,   77,  137,  261,
      136,   77,   77,  261,   77,  261,   77,   77,   77,  138,
       77,  261,  139,   77,   77,   77,  140,  261,   77,   77,
      261,   77,   77,  141,  143,   77,  142,   77,  146,  261,
       77,   77,  149,   77,  144,  145,  147,   77,  261,   77,
       77,  151,   77,   77,   77,   77,   77,  150,  261,   77,
      261,   77,  153,  148,   77,   77,  152,   77,   77,  261,

      154,   77,  155,   77,  156,   77,  157,   77,  160,  161,
       77,   77,   77,  169,   77,   77,   77,  261,  170,   77,
       77,   77,   77,  261,  160,  168,   77,   77,   77,   77,
      171,  261,  161,  261,  174,  261,   77,  261,  162,  261,
      261,   77,   77,   77,  175,  172,  173,   77,   77,  261,
       77,   77,  176,   77,  261,   77,   77,  178,   77,  261,
       77,   77,  177,  179,   77,   77,   77,   77,  261,  261,
       77,  261,   77,  261,   77,   77,   77,   77,   77,   77,
      180,  199,   77,  181,   77,  182,   77,   77,   77,   77,
       77,   77,   77,  261,   77,  183,   77,  199,   77,  261,

       77,   77,   77,  261,   77,   77,  184,  261,   77,  185,
      261,  199,   77,   77,   77,   77,  186,  187,   77,  188,
       77,  261,   77,  261,   77,   77,   77,   77,   77,  192,
      189,   77,   77,  261,   77,  261,   77,   77,   77,   77,
       77,  261,  190,   77,  191,  261,   77,  194,   77,  193,
      196,  195,   77,  160,  199,   77,  261,   77,   77,   77,
      261,   77,  261,   77,  261,   77,   77,   77,  197,  160,
      199,   77,   77,  261,   77,   77,  203,  261,   77,   77,
       77,  261,   77,  160,  199,   77,   77,   77,   77,  261,
       77,   77,   77,  261,   77,  205,  204,   77,   77,   77,

       77,  261,  261,   77,  261,   77,   77,   77,  206,  207,
       77,   77,   77,  261,   77,   77,  261,   77,  261,  261,
       77,  261,   77,   77,   77,  208,   77,   77,   77,   77,
      261,   77,  209,   77,   77,  261,   77,   77,  210,   77,
       77,   77,   77,  261,   77,  211,  261,  261,   77,  261,
      261,   77,  261,   77,   77,  261,  212,   77,   77,  213,
       77,   77,  215,  261,  261,   77,   77,  261,   77,   77,
      214,   77,   77,   77,  216,  218,   77,  217,  222,   77,
       77,   77,   77,  219,   77,   77,   77,  220,   77,   77,
      261,   77,   77,   77,   77,  261,   77,   77,  261,   77,

       77,  221,   77,  261,   77,   77,   77,   77,  224,   77,
      223,   77,   77,  261,   77,  261,   77,   77,  261,   77,
       77,   77,   77,   77,  227,   77,   77,  229,   77,  261,
       77,  228,  261,   77,   77,   77,   77,   77,  230,   77,
       77,  231,   77,  261,   77,  261,  261,   77,   77,   77,
       77,   77,  261,   77,  261,  261,   77,  232,   77,  233,
       77,  234,   77,   77,   77,  261,  235,   77,   77,  261,
       77,   77,   77,   77,  261,  239,   77,  236,   77,   77,
       77,   77,  237,  261,   77,   77,  261,   77,  238,   77,
       77,  261,   77,   77,  240,  261,   77,   77,  261,   77,

       77,  261,   77,   77,  241,   77,  261,   77,  242,   77,
       77,   77,   77,   77,   77,  261,   77,   77,   77,   77,
      261,   77,   77,   77,   77,   77,   77,   77,  245,  246,
       77,  261,  261,   77,  247,   77,  261,   77,   77,   77,
      248,  261,   77,   77,  261,   77,   77,   77,   77,   77,
       77,   77,  261,   77,   77,  261,   77,   77,   77,   77,
       77,   77,   77,   77,  261,   77,  249,  261,   77,   77,
       77,   77,  261,  250,   77,  261,   77,   77,  261,   77,
      251,   77,   77,   77,   77,  254,   77,  261,   77,   77,
      261,   77,   77,  261,   77,  261,   77,   77,   77,  255,

       77,  261,   77,  257,  261,   77,  256,   77,   77,   77,
       77,   77,  258,   77,  261,   77,   77,   77,   77,   77,
       77,   77,   77,   77,  261,   77,   77,   77,  261,  261,
      261,   77,   77,   77,   45,   45,   45,   45,   45,   77,
       77,   77,   76,   76,  109,  261,  109,  109,  109,    7,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261
    } ;

static const flex_int16_t yy_chk[1008] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,   17,
        3,    4,    4,   14,    4,    5,    5,   17,    5,    6,
        6,   18,    6,  267,   14,   23,   23,  266,   18,   18,
       25,   25,  111,  111,   26,    3,   26,   26,   26,    4,
      112,  112,  259,    5,   22,   22,   22,    6,   21,   21,

      253,   28,   28,   26,   28,   62,   22,   22,   63,  244,
       21,   21,   21,   29,  243,   29,   29,   29,  158,  158,
      226,   62,   22,  225,   63,   30,   21,   30,   30,   30,
       22,  202,   29,  201,   21,   62,   22,   21,   63,   31,
       21,   31,   31,   31,   30,  167,  166,  165,   32,   35,
      126,   29,   32,  125,  124,   32,   35,   33,   31,   31,
       30,   32,   35,   81,   33,   80,   31,   33,   37,   33,
       33,   79,   31,   34,   75,   37,   74,   36,   33,   70,
       34,   37,   36,   34,   36,   39,   34,   38,   40,   36,
       36,   38,   39,   39,   38,   40,   41,   59,   39,   42,

       38,   40,   39,   41,   43,   39,   42,   44,   41,   41,
       40,   43,   42,   61,   61,   27,   24,   43,   20,   19,
       77,   44,   65,   67,   68,   61,   61,   77,   44,   16,
       66,   66,   66,   77,   44,   69,   13,   10,   65,   67,
       68,   61,   66,   66,    7,   44,   48,    0,  116,   61,
       48,   69,   65,   67,   68,   61,   48,   48,   66,    0,
       82,    0,   48,   85,  116,   69,   66,   82,    0,    0,
       85,   48,   66,   82,   48,   48,   85,   82,  116,   48,
        0,   83,    0,   84,    0,   83,   48,  119,   83,   48,
       84,   48,    0,   48,   83,   48,   84,   86,   48,   84,

       87,   88,    0,  119,   86,   87,    0,   87,   88,   86,
       86,   89,    0,   87,   88,   90,    0,  119,   89,   88,
        0,    0,   90,   91,   89,   92,    0,   89,   90,    0,
       91,    0,   92,   90,   93,   94,   91,   95,   92,    0,
       91,   93,   94,    0,   95,    0,   96,   93,   94,   93,
       95,    0,   94,   96,   97,   99,   96,    0,   98,   96,
        0,   97,   99,   96,   98,   98,   97,   97,   99,    0,
      100,   98,  101,  102,   98,   98,  100,  100,    0,  101,
      102,  102,  103,  100,  104,  101,  102,  101,    0,  103,
        0,  104,  104,  100,  105,  103,  103,  104,  106,    0,

      104,  105,  105,  108,  105,  106,  106,  105,  118,  118,
      108,  106,  127,  128,  129,  130,  108,    0,  129,  127,
      128,  129,  130,    0,  118,  127,  128,  129,  130,  131,
      130,    0,  118,    0,  132,    0,  131,    0,  118,    0,
        0,  132,  131,  133,  133,  131,  131,  132,  134,    0,
      133,  135,  134,  136,    0,  134,  133,  136,  135,    0,
      136,  134,  135,  137,  135,  138,  136,  139,    0,    0,
      137,    0,  138,    0,  139,  140,  137,  141,  138,  142,
      139,  160,  140,  140,  141,  142,  142,  143,  140,  144,
      141,  145,  142,    0,  143,  143,  144,  160,  145,    0,

      143,  146,  144,    0,  145,  147,  144,    0,  146,  145,
        0,  160,  147,  149,  146,  148,  146,  147,  147,  148,
      149,    0,  148,    0,  150,  152,  149,  151,  148,  152,
      149,  150,  152,    0,  151,    0,  153,  150,  152,  154,
      151,    0,  150,  153,  151,    0,  154,  154,  155,  153,
      156,  155,  154,  161,  163,  155,    0,  156,  157,  168,
        0,  155,    0,  156,    0,  157,  168,  169,  157,  161,
      163,  157,  168,    0,  169,  170,  169,    0,  171,  172,
      169,    0,  170,  161,  163,  171,  172,  173,  170,    0,
      174,  171,  172,    0,  173,  173,  172,  174,  176,  175,

      173,    0,    0,  174,    0,  176,  175,  177,  174,  175,
      178,  176,  175,    0,  177,  179,    0,  178,    0,    0,
      177,    0,  179,  178,  180,  178,  181,  182,  179,  183,
        0,  180,  179,  181,  182,    0,  183,  180,  181,  181,
      182,  184,  183,    0,  185,  183,    0,    0,  184,    0,
        0,  185,    0,  186,  184,    0,  184,  185,  187,  185,
      186,  188,  187,    0,    0,  187,  186,    0,  188,  189,
      186,  187,  194,  190,  188,  190,  189,  189,  194,  194,
      190,  191,  189,  191,  192,  194,  190,  192,  191,  193,
        0,  192,  195,  196,  191,    0,  193,  192,    0,  195,

      196,  193,  193,    0,  197,  195,  196,  203,  197,  204,
      196,  197,  205,    0,  203,    0,  204,  197,    0,  205,
      203,  206,  204,  207,  205,  205,  208,  207,  206,    0,
      207,  206,    0,  208,  206,  209,  207,  210,  208,  208,
      211,  210,  209,    0,  210,    0,    0,  211,  209,  213,
      210,  212,    0,  211,    0,    0,  213,  211,  212,  212,
      214,  213,  213,  215,  212,    0,  215,  214,  219,    0,
      215,  218,  216,  214,    0,  219,  215,  216,  218,  216,
      217,  219,  217,    0,  218,  216,    0,  217,  218,  221,
      220,    0,  222,  217,  220,    0,  221,  220,    0,  222,

      223,    0,  221,  220,  222,  222,    0,  223,  223,  224,
      227,  229,  228,  223,  230,    0,  224,  227,  229,  228,
        0,  230,  224,  227,  229,  228,  231,  230,  227,  228,
      232,    0,    0,  231,  232,  234,    0,  232,  233,  231,
      233,    0,  234,  232,    0,  233,  235,  236,  234,  237,
      238,  233,    0,  235,  236,    0,  237,  238,  239,  235,
      236,  240,  237,  238,    0,  239,  240,    0,  240,  241,
      242,  239,    0,  241,  240,    0,  241,  242,    0,  246,
      242,  245,  241,  242,  247,  245,  246,    0,  245,  248,
        0,  247,  246,    0,  245,    0,  248,  247,  249,  247,

      250,    0,  248,  250,    0,  249,  248,  250,  251,  254,
      255,  249,  251,  250,    0,  251,  254,  255,  256,  257,
      258,  251,  254,  255,    0,  256,  257,  258,    0,    0,
        0,  256,  257,  258,  262,  262,  262,  262,  262,  263,
      263,  263,  264,  264,  265,    0,  265,  265,  265,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 3 "lexer.l"
#include "tokens-manual.h"
#define INTLONG 500
#define LLU 501
#define newline 600
#define PUNCTUATION 601
char* yylval;
char* placeholder;
#line 776 "lex.yy.c"

#line 778 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define CHAR 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 12 "lexer.l"


#line 1000 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 262 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 950 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 14 "lexer.l"
{yylval = strdup(yytext); return NAME;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "lexer.l"
{BEGIN(STRING);placeholder= malloc(sizeof(char));sprintf(placeholder,"");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 16 "lexer.l"
{BEGIN(CHAR);placeholder= malloc(sizeof(char));sprintf(placeholder,"");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 17 "lexer.l"
{strcat(placeholder,&yytext[1]);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 18 "lexer.l"
{strcat(placeholder, yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 19 "lexer.l"
{long temp = strtol(yytext+1,NULL,8);char* storage=malloc(sizeof(char));
        if(temp > 255){temp = 255;}
        if(isprint(temp)==0){
                sprintf(storage,"\\%03o",temp);
        }
        else{
                sprintf(storage,"%c",temp);
        }
        strcat(placeholder,storage);free(storage);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "lexer.l"
{long temp = strtol(yytext+2,NULL,16);char* storage=malloc(sizeof(char));
        if(temp > 255){temp = 255;}
        if(isprint(temp)==0){
                sprintf(storage,"\\%03o",temp);
        }
        else{
                sprintf(storage,"%c",temp);
        }
        strcat(placeholder,storage);free(storage);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "lexer.l"
{strcat(placeholder, yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "lexer.l"
{BEGIN(INITIAL);yylval = strdup(placeholder); free(placeholder);return STRING;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "lexer.l"
{return INDSEL;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "lexer.l"
{return SHL;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "lexer.l"
{return SHR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "lexer.l"
{char * end;long temp = strtol(yytext+2,&end,16);char* storage= malloc(sizeof(char));sprintf(storage,"%ld",temp);strcat(storage,end);yylval =strdup(storage);free(storage);return NUMBER;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "lexer.l"
{yylval = strdup(yytext);return NUMBER;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "lexer.l"
{char * end;long temp = strtol(yytext,&end,8);char* storage= malloc(sizeof(char));sprintf(storage,"%ld",temp);strcat(storage,end);yylval =strdup(storage);free(storage);return NUMBER;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "lexer.l"
{return PLUSPLUS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 49 "lexer.l"
{return MINUSMINUS;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 50 "lexer.l"
{return LTEQ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 51 "lexer.l"
{return GTEQ;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 52 "lexer.l"
{return EQEQ;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 53 "lexer.l"
{return NOTEQ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 54 "lexer.l"
{return LOGAND;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 55 "lexer.l"
{return LOGOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 56 "lexer.l"
{return ELLIPSIS;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 57 "lexer.l"
{return TIMESEQ;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 58 "lexer.l"
{return DIVEQ;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 59 "lexer.l"
{return MODEQ;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 60 "lexer.l"
{return PLUSEQ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 61 "lexer.l"
{return MINUSEQ;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 62 "lexer.l"
{return SHLEQ;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 63 "lexer.l"
{return SHREQ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 64 "lexer.l"
{return OREQ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 65 "lexer.l"
{return ANDEQ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 "lexer.l"
{return XOREQ;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "lexer.l"
{return AUTO;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 68 "lexer.l"
{return BREAK;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 69 "lexer.l"
{return CASE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "lexer.l"
{return CHAR;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "lexer.l"
{return CONST;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "lexer.l"
{return CONTINUE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 73 "lexer.l"
{return DEFAULT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 74 "lexer.l"
{return DO;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 75 "lexer.l"
{return DOUBLE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 76 "lexer.l"
{return ELSE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 77 "lexer.l"
{return ENUM;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 78 "lexer.l"
{return EXTERN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 79 "lexer.l"
{return FLOAT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 80 "lexer.l"
{return FOR;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 81 "lexer.l"
{return GOTO;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 82 "lexer.l"
{return IF;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 83 "lexer.l"
{return INLINE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 84 "lexer.l"
{return INT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 85 "lexer.l"
{return LONG;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 86 "lexer.l"
{return REGISTER;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 87 "lexer.l"
{return RESTRICT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 88 "lexer.l"
{return RETURN;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 89 "lexer.l"
{return SHORT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 90 "lexer.l"
{return SIGNED;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 91 "lexer.l"
{return SIZEOF;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 92 "lexer.l"
{return STATIC;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 93 "lexer.l"
{return STRUCT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 94 "lexer.l"
{return SWITCH;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 95 "lexer.l"
{return TYPEDEF;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 96 "lexer.l"
{return UNION;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 97 "lexer.l"
{return UNSIGNED;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 98 "lexer.l"
{return VOID;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 99 "lexer.l"
{return VOLATILE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 100 "lexer.l"
{return WHILE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 101 "lexer.l"
{return _BOOL;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 102 "lexer.l"
{return _COMPLEX;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 103 "lexer.l"
{return _IMAGINARY;}
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 104 "lexer.l"
{return newline;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 105 "lexer.l"
{yylval = strdup(yytext);return PUNCTUATION;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 106 "lexer.l"
{yylval = strdup(yytext); return IDENT;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 107 "lexer.l"
{fprintf(stderr, "Error: Unknown token %s\n", yytext);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 109 "lexer.l"
ECHO;
	YY_BREAK
#line 1454 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 262 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 262 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 261);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 109 "lexer.l"

main(){
        int t;
        yylval = malloc(1024);
        int line = 1;
        char* name = "stdin";
        printf("File name is %s\n", __FILE__);
        while (t = yylex())
        {
                switch(t)
                        {
                                case NAME: printf("Name is %s\n", yylval); name = yylval; break;
                                case newline: line = line + 1; break;
                                case INDSEL: printf("%s\t\%d\tINDSEL\n",name,line); break;
                                case IDENT:printf("%s\t%d\tIDENT\t%s\n",name,line,yylval); break;
                                case STRING: printf("%s\t%d\tSTRING\t%s\n",name,line,yylval); break;
                                case PUNCTUATION: printf("%s\t%d\t%s\n",name,line,yylval); break;
                                case SHL:printf("%s\t%d\tSHL\n", name, line); break;
                                case SHR: printf("%s\t%d\tSHR\n", name, line); break;
                                case '+': printf("%s\t%d\t+\n",name,line); break;
                                case '-': printf("%s\t%d\t-\n",name, line); break;
                                case PLUSPLUS: printf("%s\t%d\tPLUSPLUS\n", name, line); break;
                                case MINUSMINUS:printf("%s\t%d\tMINUSMINUS\n", name, line); break;
                                case LTEQ: printf("%s\t%d\tLTEQ\n", name, line); break;
                                case GTEQ: printf("%s\t%d\tGTEQ\n", name, line); break;
                                case EQEQ: printf("%s\t%d\tEQEQ\n", name, line); break;
                                case NOTEQ: printf("%s\t%d\tNOTEQ\n", name, line); break;
                                case LOGAND: printf("%s\t%d\tLOGAND\n", name, line); break;
                                case LOGOR: printf("%s\t%d\tLOGOR\n", name, line); break;
                                case ELLIPSIS: printf("%s\t%d\tELLIPSIS\n", name, line); break;
                                case TIMESEQ: printf("%s\t%d\tTIMESEQ\n", name, line); break;
                                case DIVEQ: printf("%s\t%d\tDIVEQ\n", name, line); break;
                                case MODEQ:printf("%s\t%d\tMODEQ\n", name, line); break;
                                case PLUSEQ: printf("%s\t%d\tPLUSEQ\n", name, line); break;
                                case MINUSEQ: printf("%s\t%d\tMINUSEQ\n", name, line); break;
                                case SHLEQ: printf("%s\t%d\tSHLEQ\n", name, line); break;
                                case SHREQ: printf("%s\t%d\tSHREQ\n", name, line); break;
                                case ANDEQ: printf("%s\t%d\tANDEQ\n", name, line); break;
                                case OREQ: printf("%s\t%d\tOREQ\n", name, line); break;
                                case XOREQ: printf("%s\t%d\tXOREQ\n", name, line); break;
                                case NUMBER:;
                                        int charCount =0;
                                        char* type = malloc(1024);
                                        if((strchr(yylval,'U') != NULL) || (strchr(yylval,'u') != NULL))
                                        {
                                                strcat(type,"UNSIGNED,");
                                                charCount++;
                                        }
                                        if(strstr(yylval,"LL") != NULL)
                                        {
                                                strcat(type,"LONGLONG");
                                                charCount+=2;

                                        }
                                        else if( (strchr(yylval,'L') != NULL) || (strchr(yylval,'l') != NULL))
                                        {
                                                strcat(type,"LONG");
                                                charCount++;

                                        }
                                        else{

                                                strcat(type,"INT");
                                        }
                                        
                                        if(charCount!=0){yylval[strlen(yylval)-charCount] = '\0';}
                                        printf("%s\t%d\tNUMBER\tINTEGER\t%s\t%s\n",name,line, yylval,type);
                                        break;
                                case INTLONG:
                                        yylval[strlen(yylval)-1] = '\0';
                                        printf("%s\t%d\tNUMBER\tINTEGER\t%d\tLONG\n", name, line, atoi(yylval)); break;
                                case LLU:
                                        yylval[strlen(yylval)-3] = '\0';
                                        printf("%s\t%d\tNUMBER\tINTEGER\t%d\tUNSIGNED,LONGLONG\n", name, line, atoi(yylval)); break;
                                case AUTO: printf("%s\t%d\tAUTO\n", name, line); break;
                                case BREAK: printf("%s\t%d\tBREAK\n", name,line); break;
                                case CASE: printf("%s\t%d\tCASE\n", name, line); break;
                                case CHAR: printf("%s\t%d\tCHAR\n", name,line); break;
                                case CONST: printf("%s\t%d\tCONST\n", name, line); break;
                                case CONTINUE: printf("%s\t%d\tCONTINUE\n", name, line); break;
                                case DEFAULT: printf("%s\t%d\tDEFAULT\n",name, line); break;
                                case DO: printf("%s\t%d\tDO\n", name, line); break;
                                case DOUBLE: printf("%s\t%d\tDOUBLE\n", name, line); break;
                                case ELSE: printf("%s\t%d\tELSE\n",name, line); break;
                                case ENUM: printf("%s\t%d\tENUM\n", name, line); break;
                                case EXTERN: printf("%s\t%d\tEXTERN\n", name, line); break;
                                case FLOAT: printf("%s\t%d\tFLOAT\n", name, line); break;
                                case FOR: printf("%s\t%d\tFOR\n", name, line); break;
                                case GOTO: printf("%s\t%d\tGOTO\n", name, line); break;
                                case IF: printf("%s\t%d\tIF\n", name, line); break;
                                case INLINE: printf("%s\t%d\tINLINE\n", name, line); break;
                                case INT: printf("%s\t%d\tINT\n", name, line); break;
                                case LONG: printf("%s\t%d\tLONG\n", name, line); break;
                                case REGISTER: printf("%s\t%d\tREGISTER\n", name, line); break;
                                case RESTRICT: printf("%s\t%d\tRESTRICT\n", name, line); break;
                                case RETURN: printf("%s\t%d\tRETURN\n", name, line); break;
                                case SHORT: printf("%s\t%d\tSHORT\n", name, line); break;
                                case SIGNED: printf("%s\t%d\tSIGNED\n", name, line); break;
                                case SIZEOF: printf("%s\t%d\tSIZEOF\n", name, line); break;
                                case STATIC: printf("%s\t%d\tSTATIC\n", name, line); break;
                                case STRUCT: printf("%s\t%d\tSTRUCT\n", name, line); break;
                                case SWITCH: printf("%s\t%d\tSWITCH\n", name, line); break;
                                case TYPEDEF: printf("%s\t%d\tTYPEDEF\n", name, line); break;
                                case UNION: printf("%s\t%d\tUNION\n", name, line); break;
                                case UNSIGNED: printf("%s\t%d\tUNSIGNED\n",name,line); break;
                                case VOID: printf("%s\t%d\tUNION\n", name, line); break;
                                case VOLATILE: printf("%s\t%d\tVolatile\n", name, line); break;
                                case WHILE: printf("%s\t%d\tWHILE\n", name, line);break;
                                case _BOOL: printf("%s\t%d\t_BOOL\n", name, line); break;
                                case _COMPLEX: printf("%s\t%d\t_COMPLEX\n", name, line); break;
                                case _IMAGINARY: printf("%s\t%d\t_IMAGINARY\n",name,line); break;
                        }

        }




}

